// Writes src/vault/errors.ts from the vault's contracts/vault/src/error.rs, so error codes come
// from the contract source rather than from memory. Usage: node scripts/vault-errors.ts <error.rs>
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export function parseVaultErrors(source: string): Map<number, string> {
  const body = /pub enum Error \{([^}]*)\}/.exec(source)?.[1];
  if (body === undefined) throw new Error("no `pub enum Error` in the source");
  const errors = new Map<number, string>();
  for (const [, name, code] of body.matchAll(/^\s*([A-Za-z]+)\s*=\s*(\d+),/gm)) {
    errors.set(Number(code), name as string);
  }
  return errors;
}

function render(errors: Map<number, string>): string {
  const lines = [...errors].map(([code, name]) => `  ${code}: "${name}",`).join("\n");
  return (
    "// The vault's contract errors by code, from contracts/vault/src/error.rs. Generated by\n" +
    "// scripts/vault-errors.ts; do not edit.\n" +
    "const VAULT_ERRORS: Readonly<Record<number, string>> = {\n" +
    lines +
    "\n};\n\n" +
    "export function vaultErrorName(code: number): string | undefined {\n" +
    "  return VAULT_ERRORS[code];\n" +
    "}\n"
  );
}

if (process.argv[1] === import.meta.filename) {
  const source = process.argv[2];
  if (source === undefined) throw new Error("usage: node scripts/vault-errors.ts <error.rs>");
  const out = join(import.meta.dirname, "..", "src", "vault", "errors.ts");
  writeFileSync(out, render(parseVaultErrors(readFileSync(source, "utf8"))));
  console.log(`wrote ${out}`);
}
