// Writes src/poseidon2-constants.ts from the circuit's constant file, so the SDK and the circuit
// share one source of round constants. test/unit/poseidon2.test.ts fails if the two drift apart.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SDK = join(import.meta.dirname, "..");
export const CIRCOM_CONSTANTS = join(
  SDK,
  "..",
  "circuits",
  "lib",
  "poseidon2",
  "poseidon2_const.circom",
);
const OUT = join(SDK, "src", "poseidon2-constants.ts");

export interface WidthConstants {
  full: bigint[][];
  partial: bigint[];
  diag: bigint[];
}

function block(source: string, fn: string, t: number): bigint[] {
  const body = source.slice(source.indexOf(`function ${fn}(t)`));
  const start = body.indexOf(`if (t==${t})`);
  const end = body.indexOf("} else", start);
  return [...body.slice(start, end).matchAll(/0x[0-9a-fA-F]+/g)].map((m) => BigInt(m[0]));
}

export function parseCircomConstants(source: string): Record<number, WidthConstants> {
  const out: Record<number, WidthConstants> = {};
  for (const t of [2, 3, 4]) {
    const full = block(source, "POSEIDON_FULL_ROUNDS", t);
    out[t] = {
      full: Array.from({ length: 8 }, (_, r) => full.slice(r * t, (r + 1) * t)),
      partial: block(source, "POSEIDON_PARTIAL_ROUNDS", t),
      diag: block(source, "POSEIDON_INTERNAL_MAT_DIAG", t),
    };
  }
  return out;
}

const hex = (x: bigint): string => "0x" + x.toString(16).padStart(64, "0") + "n";
const list = (xs: bigint[], indent: string): string =>
  "[\n" + xs.map((x) => `${indent}  ${hex(x)},\n`).join("") + `${indent}]`;

function render(constants: Record<number, WidthConstants>): string {
  const widths = [2, 3, 4].map((t) => {
    const c = constants[t] as WidthConstants;
    const full = c.full.map((round) => `      ${list(round, "      ")},\n`).join("");
    return (
      `  ${t}: {\n` +
      `    full: [\n${full}    ],\n` +
      `    partial: ${list(c.partial, "    ")},\n` +
      `    diag: ${list(c.diag, "    ")},\n` +
      `  },\n`
    );
  });
  return (
    "// Poseidon2 parameters over BN254 for t = 2, 3 and 4: the round constants of the Horizen Labs\n" +
    "// reference script and the internal matrix diagonal minus one, as\n" +
    "// circuits/lib/poseidon2/poseidon2_const.circom lists them. Generated by\n" +
    "// scripts/poseidon2-constants.ts; do not edit.\n\n" +
    "export interface Poseidon2Width {\n" +
    "  readonly full: readonly (readonly bigint[])[];\n" +
    "  readonly partial: readonly bigint[];\n" +
    "  readonly diag: readonly bigint[];\n" +
    "}\n\n" +
    "export const POSEIDON2_CONSTANTS: Readonly<Record<2 | 3 | 4, Poseidon2Width>> = {\n" +
    widths.join("") +
    "};\n"
  );
}

if (process.argv[1] === import.meta.filename) {
  writeFileSync(OUT, render(parseCircomConstants(readFileSync(CIRCOM_CONSTANTS, "utf8"))));
  console.log(`wrote ${OUT}`);
}
