use soroban_sdk::contracterror;

#[contracterror]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    BadConfig = 1,
    BadLimits = 2,
    OutflowDecrease = 3,
    Reentered = 4,
    Halted = 5,
    DepositsPaused = 6,
    TransfersPaused = 7,
    NonEmptyRoot = 8,
    BadAmount = 9,
    BadFee = 10,
    BadParties = 11,
    WrongVault = 12,
    WrongNetwork = 13,
    BadCiphertext = 14,
    DepositTooLarge = 15,
    DepositorDailyLimit = 16,
    TvlCapExceeded = 17,
    OutflowLimit = 18,
    BadArity = 19,
    NonCanonical = 20,
    DuplicateNullifier = 21,
    DuplicateCommitment = 22,
    Expired = 23,
    UnknownRoot = 24,
    TreeFull = 25,
    NullifierSpent = 26,
    ExtDataHashMismatch = 27,
    PublicAmountMismatch = 28,
    InvalidProof = 29,
    UnknownDeposit = 30,
    NotFlagged = 31,
    BadReason = 32,
    BadAttestation = 33,
    BadIds = 34,
    HaltCooldown = 35,
    NotHalted = 36,
    NoQueuedLimits = 37,
    LimitsNotReady = 38,
    Overflow = 39,
}
