use soroban_sdk::contracterror;

/// Codes start at 100, clear of the small codes of the Stellar Asset Contract, whose errors reach
/// callers unchanged when one of its plain transfers fails a call.
#[contracterror]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    BadConfig = 100,
    BadLimits = 101,
    OutflowDecrease = 102,
    Halted = 103,
    DepositsPaused = 104,
    TransfersPaused = 105,
    NonEmptyRoot = 106,
    BadAmount = 107,
    BadFee = 108,
    BadParties = 109,
    WrongVault = 110,
    WrongNetwork = 111,
    BadCiphertext = 112,
    DepositTooLarge = 113,
    DepositorDailyLimit = 114,
    TvlCapExceeded = 115,
    BadArity = 116,
    NonCanonical = 117,
    DuplicateNullifier = 118,
    DuplicateCommitment = 119,
    Expired = 120,
    UnknownRoot = 121,
    TreeFull = 122,
    NullifierSpent = 123,
    ExtDataHashMismatch = 124,
    PublicAmountMismatch = 125,
    InvalidProof = 126,
    UnknownDeposit = 127,
    NotFlagged = 128,
    BadReason = 129,
    BadAttestation = 130,
    BadIds = 131,
    HaltCooldown = 132,
    NotHalted = 133,
    NoQueuedLimits = 134,
    LimitsNotReady = 135,
    Overflow = 136,
    ForgeableKey = 137,
    RefundTooEarly = 138,
    ExceedsAdmittedValue = 139,
    DepositTooSmall = 140,
    ExceedsDailyOutflow = 141,
    NotStranded = 142,
    NothingClaimable = 143,
    CannotReceive = 144,
}
