use soroban_sdk::contracterror;

#[contracterror]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum Error {
    BadConfig = 1,
    BadLimits = 2,
    OutflowDecrease = 3,
    Halted = 4,
    DepositsPaused = 5,
    TransfersPaused = 6,
    NonEmptyRoot = 7,
    BadAmount = 8,
    BadFee = 9,
    BadParties = 10,
    WrongVault = 11,
    WrongNetwork = 12,
    BadCiphertext = 13,
    DepositTooLarge = 14,
    DepositorDailyLimit = 15,
    TvlCapExceeded = 16,
    OutflowLimit = 17,
    BadArity = 18,
    NonCanonical = 19,
    DuplicateNullifier = 20,
    DuplicateCommitment = 21,
    Expired = 22,
    UnknownRoot = 23,
    TreeFull = 24,
    NullifierSpent = 25,
    ExtDataHashMismatch = 26,
    PublicAmountMismatch = 27,
    InvalidProof = 28,
    UnknownDeposit = 29,
    NotFlagged = 30,
    BadReason = 31,
    BadAttestation = 32,
    BadIds = 33,
    HaltCooldown = 34,
    NotHalted = 35,
    NoQueuedLimits = 36,
    LimitsNotReady = 37,
    Overflow = 38,
    ForgeableKey = 39,
}
