extern crate std;

use serde_json::Value;
use soroban_sdk::{Bytes, Env, U256};

use crate::{hash, modulus, Compressor};

// Generated by the circuit's JavaScript reference, which the circuit tests check against the
// circom templates.
const NOTE_VECTORS: &str = include_str!("../../../circuits/test/vectors/notes.json");
const KEY_VECTORS: &str = include_str!("../../../circuits/test/vectors/keys.json");

const TAG_COMMITMENT: u32 = 0x01;
const TAG_NULLIFIER: u32 = 0x02;
const TAG_PKD: u32 = 0x05;
const TAG_NK: u32 = 0x06;
const TAG_AK: u32 = 0x07;
const TAG_GD: u32 = 0x08;
const TAG_ADDRESS: u32 = 0x09;

fn field(env: &Env, v: &Value) -> U256 {
    let hex = v.as_str().unwrap().trim_start_matches("0x");
    let mut bytes = [0u8; 32];
    for (i, byte) in bytes.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&hex[2 * i..2 * i + 2], 16).unwrap();
    }
    U256::from_be_bytes(env, &Bytes::from_array(env, &bytes))
}

fn hex(env: &Env, s: &str) -> U256 {
    field(env, &Value::from(s))
}

fn fold(env: &Env, point: &Value, tag: u32) -> U256 {
    hash(
        env,
        &[field(env, &point["x"]), field(env, &point["y"])],
        tag,
    )
}

#[test]
fn compress_matches_the_known_answer() {
    let env = Env::default();
    let out = Compressor::new(&env).compress(&U256::from_u32(&env, 7), &U256::from_u32(&env, 11));
    assert_eq!(
        out,
        hex(
            &env,
            "0x0960972bcfa9d858be6a1cca2c850d2eb0e5df1ad309192beeb95f8be328945f"
        )
    );
}

// Values from circuits/reference/poseidon2.mjs, for each width the hash mode supports.
#[test]
fn hash_mode_matches_the_reference_for_every_width() {
    let env = Env::default();
    let n = |x| U256::from_u32(&env, x);
    let cases = [
        (
            std::vec![n(7)],
            1,
            "0x29852d87fbf8a3c387b0694d7fe057ba05e31602398a5ab91da9d4786500bc6f",
        ),
        (
            std::vec![n(1), n(2)],
            3,
            "0x0a799a621cac2cea1ec6fdbcd5dc92cadd31c210c912aaca009aca578d210768",
        ),
        (
            std::vec![n(1), n(2), n(3)],
            4,
            "0x224785a48a72c75e2cbb698143e71d5d41bd89a2b9a7185871e39a54ce5785b1",
        ),
    ];
    for (inputs, tag, expected) in cases {
        assert_eq!(hash(&env, &inputs, tag), hex(&env, expected));
    }
}

#[test]
fn note_commitments_and_nullifiers_match_the_vectors() {
    let env = Env::default();
    let v: Value = serde_json::from_str(NOTE_VECTORS).unwrap();
    let nk_fold = field(&env, &v["owner"]["nk_fold"]);
    for note in v["notes"].as_array().unwrap() {
        let gd_fold = fold(&env, &note["g_d"], TAG_GD);
        let pkd_fold = fold(&env, &note["pk_d"], TAG_PKD);
        assert_eq!(gd_fold, field(&env, &note["g_d_fold"]));
        assert_eq!(pkd_fold, field(&env, &note["pk_d_fold"]));
        let address = hash(&env, &[gd_fold, pkd_fold], TAG_ADDRESS);
        assert_eq!(address, field(&env, &note["address_fold"]));

        let value: u128 = note["value"].as_str().unwrap().parse().unwrap();
        let cm = hash(
            &env,
            &[
                U256::from_u128(&env, value),
                address,
                field(&env, &note["rcm"]),
            ],
            TAG_COMMITMENT,
        );
        assert_eq!(cm, field(&env, &note["cm"]));
        let pos = U256::from_u32(&env, note["pos"].as_u64().unwrap() as u32);
        let nf = hash(&env, &[cm, pos, nk_fold.clone()], TAG_NULLIFIER);
        assert_eq!(nf, field(&env, &note["nf"]));
    }
}

#[test]
fn key_folds_match_the_vectors() {
    let env = Env::default();
    let v: Value = serde_json::from_str(KEY_VECTORS).unwrap();
    for account in v["accounts"].as_array().unwrap() {
        assert_eq!(
            fold(&env, &account["ak"], TAG_AK),
            field(&env, &account["ak_fold"])
        );
        assert_eq!(
            fold(&env, &account["nk"], TAG_NK),
            field(&env, &account["nk_fold"])
        );
    }
}

#[test]
fn zero_subtree_roots_match_the_reference() {
    let env = Env::default();
    let h = Compressor::new(&env);
    let v: Value = serde_json::from_str(NOTE_VECTORS).unwrap();
    let zeros = v["merkle"]["zeros"].as_array().unwrap();
    assert_eq!(
        zeros.len() as u64,
        v["merkle"]["levels"].as_u64().unwrap() + 1
    );

    let mut node = U256::from_u32(&env, 0);
    assert_eq!(node, field(&env, &zeros[0]));
    for expected in &zeros[1..] {
        node = h.compress(&node, &node);
        assert_eq!(node, field(&env, expected));
    }
}

#[test]
fn leaf_pairs_match_the_reference_roots() {
    let env = Env::default();
    let h = Compressor::new(&env);
    let v: Value = serde_json::from_str(NOTE_VECTORS).unwrap();
    let merkle = &v["merkle"];
    let zeros: std::vec::Vec<U256> = merkle["zeros"]
        .as_array()
        .unwrap()
        .iter()
        .map(|z| field(&env, z))
        .collect();
    let leaves: std::vec::Vec<U256> = merkle["leaves"]
        .as_array()
        .unwrap()
        .iter()
        .map(|l| field(&env, l))
        .collect();
    let roots = merkle["roots_after_each_insert"].as_array().unwrap();

    // Leaves 0..4 fill the leftmost subtree of height 2; every level above pairs it with zeros.
    let left = h.compress(&leaves[0], &leaves[1]);
    let right = h.compress(&leaves[2], &leaves[3]);
    let mut first = h.compress(&left, &zeros[1]);
    let mut both = h.compress(&left, &right);
    for zero in &zeros[2..zeros.len() - 1] {
        first = h.compress(&first, zero);
        both = h.compress(&both, zero);
    }
    assert_eq!(first, field(&env, &roots[1]));
    assert_eq!(both, field(&env, &roots[3]));
}

#[test]
fn compression_is_reduced_below_the_modulus() {
    let env = Env::default();
    let h = Compressor::new(&env);
    let p = modulus(&env);
    let max = p.sub(&U256::from_u32(&env, 1));
    for (l, r) in [(&max, &max), (&max, &U256::from_u32(&env, 0))] {
        assert!(h.compress(l, r) < p);
    }
}
